# Generated by Django 5.2.4 on 2025-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='entry_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='how_paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
