# Generated by Django 5.2.4 on 2025-07-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0002_contestant_entry_number_contestant_how_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='created_at',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='payment_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
